### ISSUE TITLE
Unable to run playback example code on Ubuntu 18.04 LTS. 

### ISSUE THREAD

**Issue by SongJuHeon** [UnaNancyOwen/AzureKinectSample#2]
Hi, 
I'm currenlty running some sample codes of azure kinect on Ubuntu 18.04 LTS.

These are the conditions of the environment that I'm working on:
ubuntu 18.04 LTS
Azure Kinect Sensor SDK v1.2.0
Azure Kinect Body Tracking SDK v0.9.4
OpenCV 4.1.0
cmake 3.15.4
ide: qt creator 5.12.5

While running playback example, there is some issue about 

```
case k4a_image_format_t::K4A_IMAGE_FORMAT_COLOR_MJPG:{
                // NOTE: this is slower than other formats.
                std::vector<uint8_t> buffer( src.get_buffer(), src.get_buffer() + src.get_size() );
                mat = cv::imdecode( buffer, cv::IMREAD_ANYCOLOR );
                cv::cvtColor( mat, mat, cv::COLOR_BGR2BGRA );
                break;
            } 
```
in util.h file. 

Especially, `mat = cv::imdecode( buffer, cv::IMREAD_ANYCOLOR );`  is not working (decoding problem). 

However, I tried this code on window 10 using visual studio 2019 with Azure Kinect Sensor SDK v1.2.0,  and it worked. 
It also worked with Azure Kinect Sensor SDK v1.3.0 on ubuntu 18.04 LTS.
Still, I face the same issue only on ubuntn 18.04 LTS with Azure Kinect Sensor SDK v1.2.0.

Is there any way to solve this issue? 

Thanks.

**Comment by UnaNancyOwen** [comment]
Hmmm. Sorry, I don't know why occur that problem.
Please update Azure Kinect Sensor SDK to v1.3.0 if that solves the problem.
