### ISSUE TITLE
k4a_DIR not found when configuring in cmake

### ISSUE THREAD

**Issue by tahriribraq** [UnaNancyOwen/AzureKinectSample#3]
Hi Tsukasa, when I configure your project in cmake, I keep getting the following error:

Could not find a package configuration file provided by "k4a" with any of
the following names:
k4aConfig.cmake
k4a-config.cmake
Add the installation prefix of "k4a" to CMAKE_PREFIX_PATH or set "k4a_DIR"
to a directory containing one of the above files. If "k4a" provides a
separate development package or SDK, be sure it has been installed.

As you can see in the attached CMakeLists.txt file, I've set the k4a_DIR path to the cmake folder where I installed this repo: https://github.com/microsoft/Azure-Kinect-Sensor-SDK. However, I see that the folder has a k4aConfig.cmake.ini instead of just .cmake, and I think that may be causing the error. Hopelessly stuck with this so I would REALLY appreciate it if you could tell me where you found an installation of k4a with this cmake configuration file
![cmake_error_3](https://user-images.githubusercontent.com/54651812/81527103-0972a900-931f-11ea-877e-c37bafbab4ca.JPG)

**Comment by UnaNancyOwen** [comment]
The installer of Azure Kinect Sensor SDK does not include CMake files (k4aConfig.cmake, ..., etc.) to find library.
You need to build and install Azure Kinect Sensor SDK from source code yourself.
